Docker build
Stability-AI/api-interfaces pull request #22
Opened 2022-09-26 21:36 UTC by palp

This change adds a Dockerfile to make a consistent build environment easily available.

2022-09-26 21:37 UTC, salanki commented
Will this build for both python and js?

2022-09-26 21:51 UTC, palp commented
> Will this build for both python and js?

Yeah, and thinking on it, I'd like to exclude those files from the build to ensure they get freshly compiled each run, since the output is checked in - that'd make it easily testable too.

2022-09-26 21:53 UTC, palp commented
One notable tradeoff here is that I decided on compiling protobuf and grpc rather than relying on binaries/packages - with cached images this seems fine and I think that's the best way to ensure we can have the latest versions of those cleanly.

2022-09-27 01:53 UTC, palp commented
I've added a workflow to build using this image that uploads the output as an artifact; my thinking is we could update #15 to depend on this and remove the build steps, keeping the check-in code, as well as publish the artifacts as a release - all scoped to main. This one can run on push (or PR and push to main) so there's a build check without publish.

2022-09-28 12:36 UTC, wbrown requested changes

2022-09-28 12:36 UTC, wbrown commented on Dockerfile
> +RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
Can we pull these versions up to variables?

2022-09-28 12:36 UTC, wbrown commented on Dockerfile
> +RUN rm -rf /go && wget https://go.dev/dl/go1.19.1.linux-amd64.tar.gz -qO- | tar -C / -xz
I think we're still on go1.18, and if using go1.19 imposes a dependency on that with the artifacts, it may be problematic.

2022-10-03 19:18 UTC, wbrown approved these changes

2022-10-03 19:18 UTC, merged