dpmpp sampler support
Stability-AI/api-interfaces pull request #41
Opened 2022-11-20 23:41 UTC by huo-ju

related: https://github.com/Stability-AI/stable-diffusion/pull/56

2022-11-22 17:05 UTC, pharmapsychotic approved these changes
New samplers FTW

2022-11-22 20:07 UTC, aletts approved these changes

2022-11-23 00:14 UTC, arsenetar requested changes
Conflicts need to be resolved by regenerating files after re-base/merge of main into this.

2022-11-23 15:07 UTC, huo-ju commented
Conflicts have be resolved, rebased and regenerated.

2022-11-23 15:49 UTC, pharmapsychotic approved these changes

2022-11-23 16:06 UTC, arsenetar approved these changes

2022-11-23 19:09 UTC, merged